<?php
namespace App\Providers;

use Filesystem\FileStorageServiceProvider as ServiceProvider;

class FileStorageServiceProvider extends ServiceProvider
{
	/**
	 * @throws \Exception
	 */
	public function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
	}

	/**
	 *
	 */
	public function register()
	{
		parent::register(); // TODO: Change the autogenerated stub
	}
}